### ISSUE TITLE
Good Start

### ISSUE THREAD

**Issue by joosephsky** [sabanci48/AresLibraryAllInOne#1]
Hey @sabanci48,
Good job on fast start. 
Second you need to go to settings then branches and create a branch protection rule on main branch

**Comment by sabanci48** [comment]
<img width="906" alt="Screenshot 2023-04-12 at 9 28 39 PM" src="https://user-images.githubusercontent.com/110133994/231632144-34ea76b8-da6a-49ea-939d-f8309cfcc89b.png">

**Comment by sabanci48** [comment]
what should I do here ? it wants me to update to GitPro or make it public @joosephsky

**Comment by Amaraa001** [comment]
Ali, make it public. Previous project was public.

**Comment by Amore001** [comment]
> what should I do here ? it wants me to update to GitPro or make it public @joosephsky

Ali, make it public. Previous project was public as well.

**Comment by joosephsky** [comment]
Yes you can do branch protection only in public repositories.
Good job guys @sabanci48 @Amaraa001
